let myNumber = 3;
let myString = "this is a string";
let myObject = {firstname:"No", lastName:"Name", age:50};
let myBoo = false;
let x; //undefined
let myNull = null;
let myArray = ["this", " is", " object"];
console.log("The value of my variable myNumber is: " + myNumber);
console.log("The type is number");
console.log(typeof myNumber);
console.log("The value of myString is: " + myString);
console.log("The type is string");
console.log(typeof myString);
console.log("The value of myObject is: " + myObject);
console.log("The type is object");
console.log(typeof myObject);
console.log("The value of myBoo is: " + myBoo);
console.log("The type is Boolean");
console.log(typeof myBoo);
console.log("The value of x is: " + x);
console.log("The type is undefined");
console.log(typeof x);
console.log("The value of myNull is: " + myNull);
console.log("The type is null");
console.log(typeof myNull);
console.log("The value of myArray is: " + myArray);
console.log("The type is object");
console.log(typeof myArray);